/* Callendar For You Database */
CREATE TABLE USERS(
    ID     INT(32) NOT NULL AUTO_INCREMENT,
    Email  CHAR(32) NOT NULL,
    Pass   CHAR(82) NOT NULL,

    CONSTRAINT PRIMARY KEY (ID,Email)
);
ALTER TABLE
    USERS AUTO_INCREMENT = 1;

CREATE TABLE FILES(
	FileID		int(10)	NOT NULL	AUTO_INCREMENT,
    User_ID     INT(32) NOT NULL,
    LinkToFile  CHAR(32),

    CONSTRAINT PRIMARY KEY (FileID),
    CONSTRAINT FOREIGN KEY (User_ID) REFERENCES USERS (ID)
); ALTER TABLE
    FILES AUTO_INCREMENT = 1;
